### ISSUE TITLE
feature: choose default dark/light mode themes

### ISSUE THREAD

**Issue by AMDphreak** [danielgjackson/vscode-auto-dark-mode-windows#11]
settings should allow to choose default light/dark mode themes

**Comment by danielgjackson** [comment]
Hi,

The standard VSCode settings can be used to customize the light/dark themes:

* `workbench.preferredDarkColorTheme`
* `workbench.preferredLightColorTheme`

Before these existed, the extension used to use its own (`autoDarkMode.darkTheme`, `autoDarkMode.lightTheme`) but, once the standard ones were added, I switched to using them as I couldn't see it being that useful to use anything else.  

Have you got a use case this doesn't cover?

**Comment by rfgonzalezweb** [comment]
Could you please provide an example?

I would like to use the extension to switch between the light/dark theme from this theme, not from the vscode default ones.
Thanks!

https://marketplace.visualstudio.com/items?itemName=Heron.firefox-devtools-theme

**Comment by AMDphreak** [comment]
> Hi,
> 
> The standard VSCode settings can be used to customize the light/dark themes:
> 
> * `workbench.preferredDarkColorTheme`
> * `workbench.preferredLightColorTheme`
> 
> Before these existed, the extension used to use its own (`autoDarkMode.darkTheme`, `autoDarkMode.lightTheme`) but, once the standard ones were added, I switched to using them as I couldn't see it being that useful to use anything else.
> 
> Have you got a use case this doesn't cover?

Yes, many themes come with dark and light variations---and sometimes additional variations on those as well.
Also, it'd be nice to have a dark colored theme, because pure dark modes typically are too high contrast for me.

**Comment by danielgjackson** [comment]
To change the themes that this extension switches between:

1. Open VS Code's *Settings* with the command *Preferences: Open Settings (UI)*, or through the menu:

    * On Mac: *Code* / *Preferences* / *Settings*
    * Other OS: *File* / *Preferences* / *Settings*

2. To change the light theme that is switched to, adjust the setting: (`workbench.preferredLightColorTheme`)

    * *Workbench* / *Appearance* / *Preferred Light Color Theme*

3. To change the dark theme that is switched to, adjust the setting: (`workbench.preferredDarkColorTheme`)

    * *Workbench* / *Appearance* / *Preferred Dark Color Theme*
