### ISSUE TITLE
Change theme automatically during sunrise/sunset time

### ISSUE THREAD

**Issue by Kvaibhav01** [danielgjackson/vscode-auto-dark-mode-windows#6]
Hi Daniel, thanks for this wonderful extension. It really helps.

This is a feature request. Can we have a setting wherein a user can check if they want to schedule theme change? Like when it's sunrise in the location, the theme is set to light and at sunset it becomes dark?

**Comment by danielgjackson** [comment]
If you use the setting `window.autoDetectColorScheme` to synchronize VS Code theme with the operating system's dark mode, you may prefer to just change the OS dark mode on a schedule.  If you're using Windows, it'd be a bit hacky, but possible with something like https://www.ghacks.net/2018/12/02/windows-10-switch-between-light-and-dark-mode-automatically/

**Comment by Kvaibhav01** [comment]
Thanks for the info @danielgjackson 👍

**Comment by danielgjackson** [comment]
I also found this extension that might do the job already (just for VS Code): https://marketplace.visualstudio.com/items?itemName=timrodz.lightswitch

**Comment by Kvaibhav01** [comment]
This looks the right one. Thanks again! 😁
