### ISSUE TITLE
Disable warn/info notifications on startup

### ISSUE THREAD

**Issue by cbarrick** [danielgjackson/vscode-auto-dark-mode-windows#8]
I use this extension on macOS purely for the toggle button in the status bar.

The notifications about the past functionality of this extension are useless to me, and are annoying because they appear every time I open a new window (frequently in my workflow).

Can we remove the notifications? If not, can we limit the notification to appear only once?

**Comment by danielgjackson** [comment]
Agreed, I think it's time to remove the old functionality completely.

**Comment by danielgjackson** [comment]
Fixed in commit 0755afe and released as version 1.0.9 -- all of the old code to sync with the Windows system theme has been removed too, simplifying everything a great deal.
